### ISSUE TITLE
Support multiple arguments from cmd

### ISSUE THREAD

**Issue by oskov** [oskov/Buhanova1#11]
Необходимо сделать поддержку нескольких аргументов:
*Файл для чтения (данных)
*Файл для записи (данных)
*Режим кодирования / декодированрие
*Файл для сохранения дерева (если режим кодирования)
*Файл для загрузки дерева (если режим декодирования)
*Режим для терминального ввода (типо вместо всего этого ты просто работаешь в терминале, вводишь строку и он тебе её кодирует декодирует и выводит информацию в терминал)

**Comment by denisklyshko** [comment]
Добавлен пример того, как можно работать с аргументами. Сейчас аргумент один и является названием файла, в который мы сохраняем дерево, а потом его оттуда же забираем. Наталия, удачи!

**Comment by Markvarte** [comment]
Ого как много. Хорошо.))) Спасибо.

**Comment by oskov** [comment]
Resolved with #13
