### ISSUE TITLE
Check how far we are from our testCases

### ISSUE THREAD

**Issue by oskov** [oskov/Buhanova1#7]
Т.к. Уханова сказала, что будет использовать наши примеры с прошлого занятия для проверки в конце, нам надо понять насколько текущая версия программы расходится с тем что мы высрали тогда.

**Comment by Markvarte** [comment]
Ну на данный момент получется что, если просто заменять твою хекс строку (из скрина) на бинарную, то все тестовые строки сходятся за исключением нулей в начале. Там их то больше чем надо, то меньше, то ещё что-то. В остальном же всё сходится.
